# Generated by Django 4.2.4 on 2023-08-24 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClasificacionIncidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clasificacion_incidente', models.CharField(max_length=200, unique=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Clasificación del incidente',
                'verbose_name_plural': 'Clasificaciones de incidentes',
            },
        ),
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidad', models.CharField(max_length=200, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Entidad',
                'verbose_name_plural': 'Entidades',
            },
        ),
        migrations.CreateModel(
            name='Tecnologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tecnologia', models.CharField(max_length=200, unique=True, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Tecnología',
                'verbose_name_plural': 'Tecnologías',
            },
        ),
        migrations.CreateModel(
            name='Incidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_corto', models.CharField(max_length=150, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=400, verbose_name='Descripcion')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del incidente')),
                ('clasificacion_incidente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidente.clasificacionincidente')),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidente.entidad')),
                ('tecnologia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidente.tecnologia')),
            ],
            options={
                'verbose_name': 'Incidente',
                'verbose_name_plural': 'Incidentes',
            },
        ),
    ]
