# Generated by Django 4.2.4 on 2023-08-24 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ip', '0001_initial'),
        ('incidente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgenteUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agente_usuario', models.CharField(max_length=1000, unique=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Agente de Usuario',
                'verbose_name_plural': 'Agentes de usuario',
            },
        ),
        migrations.CreateModel(
            name='CodigoRespuestaHTTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_respuesta_HTTP', models.CharField(max_length=50, unique=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Código de Respuesta HTTP',
                'verbose_name_plural': 'Códigos de Respuesta HTTP',
            },
        ),
        migrations.CreateModel(
            name='MetodoHTTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo_HTTP', models.CharField(max_length=100, unique=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Método HTTP',
                'verbose_name_plural': 'Métodos HTTP',
            },
        ),
        migrations.CreateModel(
            name='Referencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(max_length=1000, unique=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Referencia',
                'verbose_name_plural': 'Referencias',
            },
        ),
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=500, unique=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'URL',
                'verbose_name_plural': 'URL',
            },
        ),
        migrations.CreateModel(
            name='Peticion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(verbose_name='Fecha de la peticion HTTP')),
                ('hash_peticion', models.CharField(default='64', max_length=64, unique=True, verbose_name='hash_peticion')),
                ('agente_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peticion.agenteusuario')),
                ('codigo_respuesta_HTTP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peticion.codigorespuestahttp')),
                ('direccion_IP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ip.direccionip')),
                ('incidente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidente.incidente')),
                ('metodo_HTTP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peticion.metodohttp')),
                ('referencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peticion.referencia')),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peticion.url')),
            ],
            options={
                'verbose_name': 'Petición',
                'verbose_name_plural': 'Peticiones',
            },
        ),
    ]
